export const permissionsArray = {
  account_master: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  assign_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  party_call: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  all_orders: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  quality_packaging: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  proforma_invoice: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  reports: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  inventory: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  purchase: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  history: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  designer_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  printer_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  blinder_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  booklet_blinder_task: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  setup: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  machine: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  rfq: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  purchaseorder: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  grn: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  invoice: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  receipt: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  vendorpayment: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  costing: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  opportunity: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
  },
  rework: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
    approve: false,
  },
  // Module 9: credit/debit notes get an `approve` key from the start (used
  // for the Issue action, which applies the note) -- the gap Module 8 found
  // (quotation/purchaseorder/invoice checking permissions?.approve in their
  // UI with no approve key here) was fixed for `rework` and is deliberately
  // not repeated here.
  creditnote: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
    approve: false,
  },
  debitnote: {
    view_global: false,
    view_own: false,
    create: false,
    edit: false,
    delete: false,
    approve: false,
  },
}